
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/test?current_schema=public
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: postgresql

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

server:
  port: '8081'
